# Generated by Django 6.0.3 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('telecommunications', 'Telecommunications'), ('software_dev', 'Software Development'), ('cybersecurity', 'Cybersecurity'), ('engineering', 'Engineering'), ('logistics', 'Logistics'), ('contracting', 'General Contracting')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, help_text='Optional budget range', max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, help_text='Expected timeline', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='inquiries_s_service_2d9407_idx'), models.Index(fields=['is_read'], name='inquiries_s_is_read_3b23a6_idx')],
            },
        ),
    ]
