# Generated by Django 5.2.8 on 2026-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Training Offering',
                'verbose_name_plural': 'Training Offerings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/training_consulting/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Training Project',
                'verbose_name_plural': 'Training Projects',
                'ordering': ['-completion_date', 'order'],
            },
        ),
    ]
