# Generated by Django 6.0.3 on 2026-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
