# Generated by Django 6.0.3 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-tower-mobile', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telecom Offering',
                'verbose_name_plural': 'Telecom Offerings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TelecomProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telecom Project',
                'verbose_name_plural': 'Telecom Projects',
                'ordering': ['-completion_date', 'order'],
            },
        ),
    ]
